services:
  - type: web
    name: allmare-ecommerce
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PUBLIC_URL
        sync: false
      - key: MERCADO_PAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADO_PAGO_WEBHOOK_SECRET
        sync: false
      - key: MELHOR_ENVIO_TOKEN
        sync: false
      - key: MELHOR_ENVIO_CLIENT_ID
        sync: false
      - key: MELHOR_ENVIO_CLIENT_SECRET
        sync: false
      - key: MELHOR_ENVIO_SANDBOX
        value: "false"
      - key: MELHOR_ENVIO_FROM_POSTAL_CODE
        sync: false
      - key: MELHOR_ENVIO_FROM_NAME
        sync: false
      - key: MELHOR_ENVIO_FROM_PHONE
        sync: false
      - key: MELHOR_ENVIO_FROM_EMAIL
        sync: false
      - key: MELHOR_ENVIO_FROM_DOCUMENT
        sync: false
      - key: MELHOR_ENVIO_FROM_ADDRESS
        sync: false
      - key: MELHOR_ENVIO_FROM_NUMBER
        sync: false
      - key: MELHOR_ENVIO_FROM_DISTRICT
        sync: false
      - key: MELHOR_ENVIO_FROM_CITY
        sync: false
      - key: MELHOR_ENVIO_FROM_STATE
        sync: false
