services:
  - type: web
    name: allmare-ecommerce
    runtime: node
    plan: free
    buildCommand: echo "Sem compilacao necessaria"
    startCommand: npm start
    envVars:
      - key: ADMIN_EMAIL
        value: admin@allmare.com.br
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: PUBLIC_URL
        sync: false
      - key: MERCADO_PAGO_ACCESS_TOKEN
        sync: false
      - key: MELHOR_ENVIO_TOKEN
        sync: false
      - key: MELHOR_ENVIO_FROM_POSTAL_CODE
        sync: false
